"""add content_text to file

Revision ID: 80860ecba289
Revises: efe7a79984ed
Create Date: 2025-12-18 09:37:57.248009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80860ecba289'
down_revision = 'efe7a79984ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_column('content_text')

    # ### end Alembic commands ###
